spring.application.name=healthsync
server.port=8081
logging.level.org.springframework=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/healthsync
spring.datasource.username=allenmartin
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
